# Node.js with Angular
    

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  CordovaBuild : 8.1.2,

pool:
  vmImage: 'macos-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run ionic:build
  displayName: 'npm install and build'

# - script: sudo npm install -g appcenter-cli
# - script: appcenter login --token feebdff44f99eecaa582e06442080b2621793f1d

- task: CordovaBuild@1
  inputs:
    platform: 'android'
    configuration: '$(Configuration)'
    outputPattern: 'bin'
  displayName: 'Generation of Android App'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)'
    Contents: '**/*.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  displayName: 'Copying Android App as Artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'outputs'
    artifactType: 'container'

- task: CordovaBuild@1
  inputs:
    platform: 'ios'
    configuration: '$(Configuration)'
    p12: 'Certificates.p12'
    p12pwd: $(P12password)
    provProfile: 'xcode10.mobileprovision'
    outputPattern: 'bin'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  displayName: 'Copying IOS App as Artifact'