# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install

    npm install cordova --save-dev

    npm run clean
    npm run ionic:build

    cordova platform add android@7.1.1
    
    cordova plugin remove phonegap-plugin-barcodescanner
    cordova plugin add phonegap-plugin-barcodescanner --force

    cordova plugin remove cordova-plugin-file-opener2
    cordova plugin add cordova-plugin-file-opener2 --force

    cordova build android --debug

  displayName: 'npm install and build'
